### ISSUE TITLE
Submit selected code fragment instead of whole file

### ISSUE THREAD

**Issue by SilverFire** [artspb/1d34-3v4l-pl4g1n#4]
### Use case description:

I open a PHP file and select a code block
I click RMB, then choose `3v4l();` menu option
### Current behavior:

The entire file will be submitted
### Expected behavior after feature implementation:

Only selected lines will be submitted
### Why?

It can be useful to test some dedicated part of code without creating a separate file for the case

**Comment by artspb** [comment]
Thank you for the idea.
